version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./documents:/app/documents
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}    

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=ragdb
      - POSTGRES_USER=raguser
      - POSTGRES_PASSWORD=ragpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
